In [85]:
import numpy as np

# https://www.programiz.com/python-programming/numpy

### Create Numpy Arrays

In [4]:
# Define a 1D array
my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])
# Define a 2D array
my_2d_array = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8]],
                       dtype=np.int64)
# Define a 3D array
my_3d_array = np.array([[[1, 2, 3, 4],
                         [5, 6, 7, 8]],
                        [[1, 2, 3, 4],
                         [9, 10, 11, 12]]],
                       dtype=np.int64)
# Print the 1D array
print("Printing my_array:")
print(my_array)
# Print the 2D array
print("Printing my_2d_array:")
print(my_2d_array)
# Print the 3D array
print("Printing my_3d_array:")
print(my_3d_array)

# dtype param is optional

Printing my_array:
[[1 2 3 4]
 [5 6 7 8]]
Printing my_2d_array:
[[1 2 3 4]
 [5 6 7 8]]
Printing my_3d_array:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


### Special numpy arrays

In [9]:
# Create an array of ones
ones_array = np.ones((3, 4))
print("Ones Array:")
print(ones_array)
print()

# Create an array of zeros
zeros_array = np.zeros((2, 3, 4), dtype=np.int16)
print("Zeros Array:")
print(zeros_array)
print()

# Create an array with random values
random_array = np.random.random((2, 2)) #  half-open interval [0.0, 1.0)
print("Random Array:")
print(random_array)
print()

# Create an empty array
empty_array = np.empty((3, 2))
print("Empty Array:")
print(empty_array)
print()

# Create an array of evenly-spaced values
arange_array = np.arange(10, 25, 5)  # [start], stop, [step], half-open interval [0, stop), start and step are optional
print("Arange Array:")
print(arange_array)
print()

# Create an array of evenly-spaced values
# Returns 'num' evenly spaced samples, calculated over the interval [start, stop] ie. closed interval
np.linspace(0,2,9) # start, stop and num of samples

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Zeros Array:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]

Random Array:
[[0.59060228 0.45175797]
 [0.13610939 0.06753312]]

Empty Array:
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Arange Array:
[10 15 20]



array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

### Inspect numpy arrays

In [7]:
# Create a numpy array with shape (2,4) and dtype int64
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print the number of dimensions of `my_array`
print("Number of dimensions of my_array:")
print(my_array.ndim)
print()

# Print the number of elements in `my_array`
print("Number of elements in my_array:")
print(my_array.size)
print()

# Print the shape of array
print("Shape of my_array:")
print(my_array.shape)
print()

# can deduce dimensions from shape

Number of dimensions of my_array:
2

Number of elements in my_array:
8

Shape of my_array:
(2, 4)



In [8]:
# Shape of 1d array
my_array = np.array([1,2,3,4])
my_array.shape

(4,)

### Reshape, Transpose, Unique, Append, Flatten

In [11]:
# old ndarray and new ndarray should have the same size ie. total number elements should be same
a = np.array([1,2,3, 4,5,6])
reshaped_2d_array = np.reshape(a, (3,2))
print("Reshaped 2dArray:")
print(reshaped_2d_array)

reshaped_1d_array = np.reshape(reshaped_2d_array, (6,))
print("Reshaped 1dArray:")
print(reshaped_1d_array)

Reshaped 2dArray:
[[1 2]
 [3 4]
 [5 6]]
Reshaped 1dArray:
[1 2 3 4 5 6]


In [12]:
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_2d_array`
print(my_2d_array)

# Transpose `my_2d_array`
print(np.transpose(my_2d_array))

# Or use `T` to transpose `my_2d_array`
print(my_2d_array.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [21]:
# Returns unique elements of ndarray
unique_1d_array = np.unique([1, 1, 2, 2, 3, 3])
print(unique_1d_array)

unique_2d_array = np.unique([[1, 1], [2, 4], [3, 3]]) # if axis is not specified, nd array is flattened
print(unique_2d_array)

[1 2 3]
[1 2 3 4]


In [22]:
# Return the unique rows of a nd array
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=0)  # axis = 1 returns unique columns of a 2d array

array([[1, 0, 0],
       [2, 3, 4]])

In [16]:
# Returns unique elements along with counts
a = np.array([1, 2, 6, 4, 2, 3, 2])
values, counts = np.unique(a, return_counts=True)
print(values)
print(counts)

[1 2 3 4 6]
[1 3 1 1 1]


In [17]:
# Return the indices of the original array that give the unique values:
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices = np.unique(a, return_index=True)
print(u)
print(indices)
print(a[indices])

['a' 'b' 'c']
[0 1 3]
['a' 'b' 'c']


In [23]:
my_array = np.array([1,2,3,4])

# Print `my_array` before appending
print("my_array before appending:", my_array)

# Append a 1D array to `my_array`
new_array = np.append(my_array, [7, 8, 9, 10])

# Print `new_array`
print("new_array:", new_array)

my_array before appending: [1 2 3 4]
new_array: [ 1  2  3  4  7  8  9 10]


In [24]:
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_2d_array` before appending
print("my_2d_array before appending:\n", my_2d_array)

# Append an extra column to `my_2d_array`
new_2d_array = np.append(my_2d_array, [[7], [8]], axis=1) # if axis = 0, append extra row

# Print `new_2d_array`
print("new_2d_array:\n", new_2d_array)

my_2d_array before appending:
 [[1 2 3 4]
 [5 6 7 8]]
new_2d_array:
 [[1 2 3 4 7]
 [5 6 7 8 8]]


In [25]:
x = np.ones((4,))
my_array = np.array([1,2,3,4])
# Concatenate `my_array` and `x`
print(np.concatenate((my_array,x)))

[1. 2. 3. 4. 1. 1. 1. 1.]


In [27]:
# nd arrays must be compatible along the axis we want to concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print(np.concatenate((a, b), axis=0)) # row wise
print(np.concatenate((a, b.T), axis=1)) # column wise
print(np.concatenate((a, b), axis=None)) # flattens and concatenates

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]


In [31]:
a = np.array([[1, 2], [3, 4]])
a.flatten() # np.flatten(a) does not work

array([1, 2, 3, 4])

### Indexing and Slicing

In [34]:
# NumPy Negative Array Indexing

# NumPy allows negative indexing for its array. The index of -1 refers to the last item, -2 to the second last item and so on.
numbers = np.array([1, 3, 5, 7, 9])

# access the last element
print(numbers[-1])    # prints 9

# access the second-to-last element
print(numbers[-2])    # prints 7


9
7


In [35]:
# Modify Array Elements Using Index

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10])

# change the value of the first element
numbers[0] = 12
print("After modifying first element:",numbers)

After modifying first element: [12  4  6  8 10]


In [37]:
# Indexing

# create a 2D array 
array1 = np.array([[1, 3, 5, 7], 
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])


# access the element at the second row and fourth column
element1 = array1[1, 3] 
print("4th Element at 2nd Row:",element1)  

4th Element at 2nd Row: 15


In [40]:
# Indexing

# create a 2D array 
array1 = np.array([[1, 3, 5], 
             [7, 9, 2], 
             [4, 6, 8]])

# access the second row of the array
second_row = array1[1, :]
print("Second Row:", second_row)  

# access the third column of the array
third_col = array1[:, 2]
print("Third Column:", third_col)  

# access first two row elements of third column
first_two_elements_third_col = array1[0:2, 2]
print("First two row elements of third column", first_two_elements_third_col)

Second Row: [7 9 2]
Third Column: [5 2 8]
First two row elements of third column [5 2]


In [41]:
# Slicing: 1D array
# array[start:stop:step]  Stop position is not included

# If we omit start, slicing starts from the first element
# If we omit stop, slicing continues up to the last element
# If we omit step, default step size is 1


# create a 1D array 
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

# slice array1 from index 2 to index 6 (exclusive)
print(array1[2:6])  # [5 7 8 9]

# slice array1 from index 0 to index 8 (exclusive) with a step size of 2
print(array1[0:8:2])  # [1 5 8 2]

# slice array1 from index 3 up to the last element
print(array1[3:])  # [7 8 9 2 4 6]

# items from start to end
print(array1[:])   # [1 3 5 7 8 9 2 4 6]

[5 7 8 9]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]


In [42]:
# Slicing: 2D array
# array[row_start:row_stop:row_step, col_start:col_stop:col_step]

# create a 2D array 
array1 = np.array([[1, 3, 5, 7], 
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])


# slice the array to get the first two rows and columns
subarray1 = array1[:2, :2]

# slice the array to get the last two rows and columns
subarray2 = array1[1:3, 2:4]

# print the subarrays
print("First Two Rows and Columns: \n",subarray1)
print("Last two Rows and Columns: \n",subarray2)

First Two Rows and Columns: 
 [[ 1  3]
 [ 9 11]]
Last two Rows and Columns: 
 [[13 15]
 [ 6  8]]


### Math Functions

#### Aggregate Functions

In [43]:
np.sum([1,2,3,4])

10

In [44]:
np.sum([[0, 1], [0, 5]])

6

In [45]:
np.sum([[0, 1], [0, 5]], axis=0) # column-wise

array([0, 6])

In [46]:
np.sum([[0, 1], [0, 5]], axis=1) # row-wise

array([1, 5])

In [47]:
np.max([1,2,3,4])

4

In [48]:
np.max([[0, 1], [0, 5]], axis=0) #column-wise

array([0, 5])

In [49]:
np.max([[0, 1], [0, 5]], axis=1) # row-wise

array([1, 5])

In [53]:
# create a 2D array
array1 = np.array([[2, 4, 6], 
                   [8, 10, 12], 
                   [14, 16, 18]])

# compute median along horizontal axis 
result1 = np.median(array1, axis=1)

print("Median along horizontal axis :", result1)

# compute median along vertical axis
result2 = np.median(array1, axis=0)

print("Median along vertical axis:", result2)

# compute median of entire array
result3 = np.median(array1)

print("Median of entire array:", result3)

Median along horizontal axis : [ 4. 10. 16.]
Median along vertical axis: [ 8. 10. 12.]
Median of entire array: 10.0


#### Array functions (element-wise operations on array)

In [51]:
# create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 9, 16, 25, 36])

# add the two arrays element-wise
arr_sum = np.add(array1, array2)

# subtract the array2 from array1 element-wise
arr_diff = np.subtract(array1, array2)

# compute square root of array2 element-wise
arr_sqrt = np.sqrt(array2)


print("\nSum of arrays:\n", arr_sum)
print("\nDifference of arrays:\n", arr_diff)
print("\nSquare root of second array:\n", arr_sqrt)


Sum of arrays:
 [ 5 11 19 29 41]

Difference of arrays:
 [ -3  -7 -13 -21 -31]

Square root of second array:
 [2. 3. 4. 5. 6.]


In [52]:
array1 = np.array([1, 2, 3])

# using the ** operator
result1 = array1 ** 2
print("Using the ** operator:",result1) 

# using the power() function
result2 = np.power(array1, 2)
print("Using the power() function:",result2) 

Using the ** operator: [1 4 9]
Using the power() function: [1 4 9]


### Boolean masking

In [57]:
array1 = np.array([12, 24, 16, 21, 32, 29, 7, 15])
boolean_mask = array1 > 20
print(boolean_mask)
print(array1[boolean_mask])

[False  True False  True  True  True False False]
[24 21 32 29]


In [59]:
# create a 2D  array
array1 = np.array([[1, 7, 9], 
                    [14, 19, 21], 
                    [25, 29, 35]])

# create a boolean mask based on the condition 
# that elements are greater than 9
boolean_mask = array1 > 9
print(boolean_mask)

# select only the elements that satisfy the condition
result = array1[boolean_mask]

print(result)
# returns a flattened 1D array containing only the elements that satisfy the condition


[[False False False]
 [ True  True  True]
 [ True  True  True]]
[14 19 21 25 29 35]


### Argmax, Argmin, Argsort and sort

In [66]:
my_array = np.array([4,5,6,10,3,2,1])
print("Argmax of 1d array")
print(np.argmax(my_array))

Argmax of 1d array
3


In [67]:
my_2d_array = np.array([[4,3,8], [1,9,7]])

print("Argmax of 2d array with axis=0") # column wise
print(np.argmax(my_2d_array, axis = 0))
print("Argmax of 2d array with axis=1") # row wise
print(np.argmax(my_2d_array, axis = 1))

Argmax of 2d array with axis value not specified
4
Argmax of 2d array with axis=0
[0 1 0]
Argmax of 2d array with axis=1
[2 1]


In [76]:
# To find index of maximum element in 2d array
my_2d_array = np.array([[4,3,8], [1,9,7]])
print("Argmax of 2d array with axis value = None") # flattens array
print(np.argmax(my_2d_array, axis = None))

# To find the index in 2d format
ind = np.unravel_index(np.argmax(my_2d_array, axis = None), my_2d_array.shape)
print("Index in 2d format")
print(ind)
print("Element corresponding to Index")
print(my_2d_array[ind])

Argmax of 2d array with axis value = None
4
Index in 2d format
(1, 1)
Element corresponding to Index
9


In [72]:
a = np.array([1,3,2,6,4])
np.argsort(a)

array([0, 2, 1, 4, 3])

In [96]:
a = np.array([1,3,2,6,4])
np.flip(np.argsort(a)) # argsort in descending order

array([3, 4, 1, 2, 0])

In [74]:
a = np.array([[2,1], [3,4], [6,5]])
np.argsort(a, axis = 1) # row wise

array([[1, 0],
       [0, 1],
       [1, 0]])

In [75]:
a = np.array([[2,1], [3,4], [6,5]])
np.argsort(a, axis = 0) # column wise

array([[0, 0],
       [1, 1],
       [2, 2]])

In [73]:
# 2d array 
a = np.array([[2,1], [3,4], [6,5]])
np.argsort(a, axis = None) # flattens the array and then sorts if axis = None 

array([1, 0, 2, 3, 5, 4])

In [79]:
# To find index in 2d format
ind = np.unravel_index(a.argsort(axis=None), a.shape)
print(ind)
# first element = first array's index and second array's index = [0,1]
print(a[ind])
# sorted elements

(array([0, 0, 1, 1, 2, 2]), array([1, 0, 0, 1, 1, 0]))
[1 2 3 4 5 6]


In [82]:
a = np.array([[1,4],[3,1]])
print(np.sort(a, axis = None)) # flattens 
print(np.sort(a, axis = 0))
print(np.sort(a, axis = 1))

# Note sort() in numpy does not have reverse argument unlike python

[1 1 3 4]
[[1 1]
 [3 4]]
[[1 4]
 [1 3]]


### Linear Algebra

In [ ]:
array1 = np.array([1, 3, 5])
array2 = np.array([2, 4, 6])

# use of dot() to perform array multiplication
result = np.dot(array1, array2)

print(result)

# 1*2 + 3*4 + 5*6 = 44


In [83]:
# create a 3x3 square matrix
matrix1 = np.array([[1, 3, 5], 
             		[7, 9, 2],
                    [4, 6, 8]])

# find inverse of matrix1
result = np.linalg.inv(matrix1)

print(result)

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]


In [84]:
# create a matrix
matrix1 = np.array([[1, 2, 3], 
             		[4, 5, 1],
                    [2, 3, 4]])

# find determinant of matrix1
result = np.linalg.det(matrix1)

print(result)

-4.999999999999999


### Broadcasting

In [91]:
# 1-D array
array1 = np.array([1, 2, 3])

# scalar
number = 5

# add scalar and 1-D array
sum = array1 + number

print(sum)

[6 7 8]


In [92]:
# 1-D array
array1 = np.array([1, 2, 3])

# scalar
number = 5

# multiply scalar and 1-D array
mul = array1 * number

print(mul)

[ 5 10 15]


### Vectorization

In [95]:
# define two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[0, 1, 2], [0, 1, 2]])

# add two arrays (vectorization)
array_sum = array1 + array2
array_substract = array1 - array2
array_multiply = array1 * array2

print("Sum between two arrays(element-wise):\n", array_sum)
print("Substraction between two arrays(element-wise):\n", array_substract)
print("Multiplication between two arrays(element-wise):\n", array_multiply)

Sum between two arrays(element-wise):
 [[1 3 5]
 [4 6 8]]
Substraction between two arrays(element-wise):
 [[1 1 1]
 [4 4 4]]
Multiplication between two arrays(element-wise):
 [[ 0  2  6]
 [ 0  5 12]]


### List to Numpy Array and vice-versa

In [89]:
a_list = [1,2,3,4]
print(type(a_list))
a_array = np.asarray(a_list) # or np.array(a_list)
print(type(a_array))

<class 'list'>
<class 'numpy.ndarray'>


In [90]:
a_array = np.array([1,2,3,4])
print(type(a))
a_list = a_array.tolist()
print(type(a_list))

<class 'numpy.ndarray'>
<class 'list'>
