In [5]:
import numpy as np
from numpy import random

In [6]:
# Generate X
X = random.randint(1000, size=(100,10))
X[:10]

array([[ 71, 705, 868, 982, 515, 697, 775, 340, 893, 105],
       [875, 631, 836, 745, 651, 780,   0, 927, 972, 804],
       [122, 568, 735, 199, 357, 912, 444, 560, 115, 980],
       [471, 351, 519, 614, 300, 583, 163, 868, 427, 800],
       [115, 264, 196, 883, 279, 438, 905, 244, 811, 939],
       [386, 812, 832, 777, 462, 927, 249, 953, 260, 216],
       [213, 998, 569, 581, 873, 593, 907, 728, 708,  33],
       [771, 433, 808, 895, 327, 707, 551, 361, 464, 998],
       [701, 366, 806,  78, 472, 195, 883, 445,   9, 410],
       [ 91, 416,  38, 656, 694, 721, 231, 683, 388, 380]])

In [7]:
# Generate y, should be size (r,1)
y = random.randint(2, size=(100,1))
y [:10]

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1]])

In [8]:
def train_linear_reg(X, y):
    weights = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y)
    return weights

In [9]:
wts = train_linear_reg(X, y)

In [10]:
wts

array([[ 2.13653777e-04],
       [-2.09446073e-05],
       [ 1.86083330e-04],
       [ 5.52030495e-06],
       [ 3.61738168e-05],
       [ 9.16098084e-05],
       [ 4.13925136e-05],
       [ 1.34035251e-04],
       [ 2.69260868e-04],
       [ 3.96550831e-05]])

In [11]:
def train_linear_reg_gd(X, y, learning_rate=0.001, max_epochs=10):
    num_datapoints, num_features = X.shape

    # set weights and bias to 0
    weights = np.zeros(shape=(num_features, 1))
    bias = 0

    for i in range(max_epochs):
        # Calculate simple linear combination y = mx + c or y = X * w + b
        y_predict = np.dot(X, weights) + bias  # O(r*c)
        # Use mean squared error to calculate the loss and then
        # get the average over all datapoints to get the cost
        cost = (1 / num_datapoints) * np.sum((y_predict - y) ** 2)  # O(r)

        # Calculate gradients
        # 1st - gradient with respect to weights
        grad_weights = (1 / num_datapoints) * np.dot(X.T, (y_predict - y))  # O(c⋅r)
        # 2nd - gradient with respect to bias
        grad_bias = (1 / num_datapoints) * np.sum((y_predict - y))  # O(r)

        # update weights and bias
        weights -= learning_rate * grad_weights
        bias -= learning_rate * grad_bias

    return weights, bias


In [12]:
wts, bs = train_linear_reg_gd(X, y)

In [20]:
wts

array([[-1.77285393e+30],
       [-1.97546165e+30],
       [-1.88924020e+30],
       [-2.01007497e+30],
       [-1.75743987e+30],
       [-1.74592119e+30],
       [-1.82668466e+30],
       [-1.94719702e+30],
       [-1.77167932e+30],
       [-1.80025447e+30]])

### IMP. POINTS TO NOTE
#### y shape should (r,1) and weights shape should be (c,1)
#### max_epochs should be small, else some calculation will overflow floating point calculation
#### cost can also be used as stopping criteria e.g. while cost > 0.0001 enter the loop ie. keep updating wts and bias

In [18]:
class LinearRegression:

    def __init__(self, lr = 0.001, n_iters=10):
        self.lr = lr
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros((n_features,1))
        self.bias = 0

        for _ in range(self.n_iters):
            y_pred = np.dot(X, self.weights) + self.bias

            dw = (1/n_samples) * np.dot(X.T, (y_pred-y))
            db = (1/n_samples) * np.sum(y_pred-y)

            self.weights = self.weights - self.lr * dw
            self.bias = self.bias - self.lr * db

    def predict(self, X_test):
        y_pred = np.dot(X_test, self.weights) + self.bias
        return y_pred

In [19]:
lr = LinearRegression()
lr.fit(X,y)
lr.weights

array([[-1.77285393e+30],
       [-1.97546165e+30],
       [-1.88924020e+30],
       [-2.01007497e+30],
       [-1.75743987e+30],
       [-1.74592119e+30],
       [-1.82668466e+30],
       [-1.94719702e+30],
       [-1.77167932e+30],
       [-1.80025447e+30]])

In [ ]:
# Time Complexity = O(num of epochs * num of data pts)