In [9]:
import numpy as np
from numpy import random

In [10]:
# Generate X
X = random.randint(1000, size=(100,10))
X[:10]

array([[138, 784, 314, 428, 836, 957, 449,  83, 606, 101],
       [ 59, 730, 943, 729, 179, 810, 244, 306, 270, 989],
       [190, 833, 958, 946, 790, 343,  92, 354, 157,  62],
       [801, 185,  31, 444, 239, 564,  27, 180, 282,  72],
       [930,  58, 175,  55, 741, 723, 663, 248,  35, 554],
       [519, 306,  64, 231, 907, 661, 971, 975,  69, 288],
       [586, 916, 114,  69, 546, 547, 919, 921, 847, 947],
       [347, 698, 449, 766, 523, 885, 330,  32, 287, 315],
       [883, 396, 152, 316, 529, 391, 117, 672,  24, 500],
       [662,  75, 427, 160,  14,  24,  14, 226, 513, 645]])

In [11]:
# Generate y, should be size (r,1)
y = random.randint(2, size=(100,1))
y [:10]

array([[0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0]])

In [14]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def train_log_reg_gd(X, y, learning_rate=0.001, max_epochs=10):
    num_datapoints, num_features = X.shape

    # set weights and bias to 0
    weights = np.zeros(shape=(num_features, 1))
    bias = 0

    for i in range(max_epochs):
        # Calculate simple linear combination y = mx + c or y = X * w + b
        y_predict = sigmoid(np.dot(X, weights) + bias)  # O(r*c)
        # Use mean squared error to calculate the loss and then
        # get the average over all datapoints to get the cost
        cost = (-1 / num_datapoints) * np.sum( y * np.log(y_predict)  + (1-y) * np.log(1-y_predict) )

        # Calculate gradients
        # 1st - gradient with respect to weights
        grad_weights = (1 / num_datapoints) * np.dot(X.T, (y_predict - y))  # O(c⋅r)
        # 2nd - gradient with respect to bias
        grad_bias = (1 / num_datapoints) * np.sum((y_predict - y))  # O(r)

        # update weights and bias
        weights -= learning_rate * grad_weights
        bias -= learning_rate * grad_bias

    return weights, bias


In [15]:
wts, bs = train_log_reg_gd(X, y)

<ipython-input-14-56cc17162fe5>:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


In [16]:
wts

array([[ 0.0608051 ],
       [-0.28441   ],
       [ 0.08867008],
       [-0.08053499],
       [ 0.10190012],
       [-0.31505999],
       [ 0.0474    ],
       [ 0.11125509],
       [-0.06102996],
       [-0.02677998]])

### IMP. POINTS TO NOTE
#### y shape should (r,1) and weights shape should be (c,1)
#### max_epochs should be small, else some calculation will overflow floating point calculation
#### cost can also be used as stopping criteria e.g. while cost > 0.0001 enter the loop ie. keep updating wts and bias

In [17]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

class LogisticRegression():

    def __init__(self, lr=0.001, n_iters=1000):
        self.lr = lr
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros((n_features,1))
        self.bias = 0

        for _ in range(self.n_iters):
            linear_pred = np.dot(X, self.weights) + self.bias
            predictions = sigmoid(linear_pred)

            dw = (1/n_samples) * np.dot(X.T, (predictions - y))
            db = (1/n_samples) * np.sum(predictions-y)

            self.weights = self.weights - self.lr*dw
            self.bias = self.bias - self.lr*db


    def predict(self, X):
        linear_pred = np.dot(X, self.weights) + self.bias
        y_pred = sigmoid(linear_pred)
        class_pred = [0 if y<=0.5 else 1 for y in y_pred]
        return class_pred

In [18]:
lr = LogisticRegression()
lr.fit(X,y)
lr.weights

<ipython-input-17-8cfcd0d97119>:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


array([[ 0.00189966],
       [-0.97081533],
       [ 0.30339035],
       [ 0.01528221],
       [ 0.46855051],
       [-0.63049658],
       [ 0.00452158],
       [ 0.30401437],
       [-0.07754713],
       [-0.13377653]])

In [ ]:
# Time Complexity = O(num of epochs * num of data pts)