In [ ]:
# https://machinelearningmastery.com/pytorch-tutorial-develop-deep-learning-models/
# https://jovian.ai/aakashns/02-linear-regression

In [ ]:
# Logistic Regression Implementation - https://www.deeplearningwizard.com/deep_learning/practical_pytorch/pytorch_logistic_regression/#building-a-logistic-regression-model-with-pytorch-gpu
# https://towardsdatascience.com/logistic-regression-with-pytorch-3c8bbea594be

In [2]:
#!python --version
#!pip install torch

Python 3.8.8


In [1]:
import numpy as np
import torch
from numpy import random 

In [2]:
X = random.randint(1000, size=(100,10))
X[:10]

array([[406, 217, 935, 629, 214, 517, 938, 586, 733, 625],
       [214, 769, 798, 974,  62, 872, 596, 865, 192, 694],
       [881, 390, 565, 731, 383, 346, 328, 807, 705, 241],
       [547, 975,  98, 782, 445, 101, 202, 703, 564, 648],
       [999, 108, 157, 552, 306, 790, 408, 487, 784, 670],
       [436, 831, 137, 427, 585,  65, 425, 881, 380, 612],
       [928, 397,  91, 488,  48, 947, 159, 824,  83, 699],
       [714,  78, 750, 146,  53, 200, 882, 322, 299, 801],
       [607, 560, 958, 729, 577, 292, 902, 645, 422, 768],
       [406, 709, 110, 760, 325, 836,  78, 185, 971, 406]])

In [3]:
y = random.randint(2, size=(100,1))
y [:10]


array([[1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1]])

In [4]:
# imp to convert to "float" tensor
X = torch.from_numpy(X).to(torch.float32)
y = torch.from_numpy(y).to(torch.float32)

In [5]:
# We'll create a TensorDataset, which allows access to rows from X and y as tuples, and provides standard APIs for working 
# with many different types of datasets in PyTorch
from torch.utils.data import TensorDataset

train_ds = TensorDataset(X, y)
train_ds[0:3]

(tensor([[406., 217., 935., 629., 214., 517., 938., 586., 733., 625.],
         [214., 769., 798., 974.,  62., 872., 596., 865., 192., 694.],
         [881., 390., 565., 731., 383., 346., 328., 807., 705., 241.]]),
 tensor([[1.],
         [1.],
         [0.]]))

In [6]:
# Define data loader (DataLoader can split the data into batches of a predefined size while training)
from torch.utils.data import DataLoader

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [7]:
# Provides data in batch size of 5
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[881., 390., 565., 731., 383., 346., 328., 807., 705., 241.],
        [668.,  16., 401., 159., 494., 506., 634., 724., 129., 907.],
        [676., 121., 244., 769., 288., 183., 423., 570., 643., 355.],
        [402., 820., 619., 456., 727., 681., 797., 129., 934., 429.],
        [  6., 209., 228., 515., 630., 528., 822.,  46., 799.,  52.]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])


In [8]:
# Create Model Class and instantiate it
import torch.nn as nn

class LogisticRegression(nn.Module):    
    # build the constructor
    def __init__(self, n_inputs, n_outputs):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(n_inputs, n_outputs)
    # make predictions
    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))  # note the sigmoid transformation
        return y_pred

input_dim = 10
output_dim = 1    

model = LogisticRegression(input_dim, output_dim)

In [9]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1634, -0.2264, -0.0220,  0.2848, -0.0691, -0.0577, -0.1802,  0.0483,
           0.2846,  0.2539]], requires_grad=True),
 Parameter containing:
 tensor([-0.0959], requires_grad=True)]

In [10]:
# Loss fn 
criterion = nn.BCELoss()  # binary cross entropy

In [11]:
# Optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [12]:
# Train the model

for epoch in range(5):
    # enumerate mini batches
    for i, (inputs, targets) in enumerate(train_dl):
        # clear the gradients
        optimizer.zero_grad()
        # compute the model output
        yhat = model(inputs)
        # calculate loss
        loss = criterion(yhat, targets)
        # compute gradients
        loss.backward()
        # update model weights using gradient
        optimizer.step()
        
    print('Epoch = {}, Loss = {}'.format(epoch, loss.item()))
 

Epoch = 0, Loss = 60.0
Epoch = 1, Loss = 80.0
Epoch = 2, Loss = 40.0
Epoch = 3, Loss = 60.0
Epoch = 4, Loss = 20.0


In [13]:
# Generate predictions/inference
preds = model(X[:10])
preds

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SigmoidBackward0>)

In [14]:
# saving model

torch.save(model.state_dict(), 'pytorch_logistic_regression_model.pkl')