In [ ]:
# https://machinelearningmastery.com/pytorch-tutorial-develop-deep-learning-models/


In [ ]:
# Linear Regression Implementation - https://www.deeplearningwizard.com/deep_learning/practical_pytorch/pytorch_linear_regression/#building-a-linear-regression-model-with-pytorch-gpu
# https://jovian.ai/aakashns/02-linear-regression

In [2]:
#!python --version
#!pip install torch

Python 3.8.8


In [69]:
import numpy as np
import torch
from numpy import random 

In [70]:
X = random.randint(1000, size=(100,10))
X[:10]

array([[668, 127, 638, 154, 159, 929, 766, 739, 846, 508],
       [883, 535, 396, 960, 968, 842, 174, 337, 696, 121],
       [ 97, 618, 582,  81,  97, 923, 399, 683, 495, 587],
       [902, 494, 579, 768, 721, 443,  83, 908, 301, 145],
       [944, 382, 283, 705, 738, 656, 445, 526, 653, 246],
       [501, 639, 773, 428, 256, 966, 340, 480, 360, 774],
       [492, 782, 132, 604, 965, 681, 814, 562, 139, 563],
       [832, 401, 148, 434, 401,  43, 219, 902, 301, 737],
       [141, 417, 527, 862, 141, 491, 734,   0, 269, 990],
       [972, 685,  13, 848, 305,  25, 124, 939, 942, 960]])

In [71]:
y = random.randint(20, size=(100,1))
y [:10]

array([[12],
       [ 4],
       [ 3],
       [13],
       [16],
       [ 6],
       [18],
       [ 5],
       [18],
       [19]])

In [72]:
# imp to convert to "float" tensor
X = torch.from_numpy(X).to(torch.float32)
y = torch.from_numpy(y).to(torch.float32)

In [73]:
# We'll create a TensorDataset, which allows access to rows from X and y as tuples, and provides standard APIs for working 
# with many different types of datasets in PyTorch
from torch.utils.data import TensorDataset

train_ds = TensorDataset(X, y)
train_ds[0:3]

(tensor([[668., 127., 638., 154., 159., 929., 766., 739., 846., 508.],
         [883., 535., 396., 960., 968., 842., 174., 337., 696., 121.],
         [ 97., 618., 582.,  81.,  97., 923., 399., 683., 495., 587.]]),
 tensor([[12.],
         [ 4.],
         [ 3.]]))

In [74]:
# Define data loader (DataLoader can split the data into batches of a predefined size while training)
from torch.utils.data import DataLoader

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [75]:
# Provides data in batch size of 5
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[336., 931., 780., 507., 636., 992., 214., 631., 818., 132.],
        [970., 269., 999., 768.,  76., 728., 929., 498., 384., 734.],
        [417., 938., 645., 331., 457.,  25., 362., 203., 706., 403.],
        [110., 882., 925., 393.,  90., 868.,  50., 238., 569., 220.],
        [148., 467., 341., 563., 252., 966., 997., 286., 644., 638.]])
tensor([[ 7.],
        [14.],
        [16.],
        [ 0.],
        [19.]])


In [76]:
# Create Model Class and instantiate it
import torch.nn as nn

class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)  

    def forward(self, x):
        out = self.linear(x)
        return out

input_dim = 10
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)

In [77]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1405, -0.2222,  0.2282, -0.2879, -0.2118,  0.0630, -0.1483, -0.2598,
           0.3062, -0.1258]], requires_grad=True),
 Parameter containing:
 tensor([-0.0705], requires_grad=True)]

In [80]:
# Loss fn 
criterion = nn.MSELoss()

In [82]:
# Optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

In [83]:
# Train the model

for epoch in range(5):
    # enumerate mini batches
    for i, (inputs, targets) in enumerate(train_dl):
        # clear the gradients
        optimizer.zero_grad()
        # compute the model output
        yhat = model(inputs)
        # calculate loss
        loss = criterion(yhat, targets)
        # compute gradients
        loss.backward()
        # update model weights using gradient
        optimizer.step()
        
    print('Epoch = {}, Loss = {}'.format(epoch, loss.item()))
 

Epoch = 0, Loss = 5293.462890625
Epoch = 1, Loss = 6128.298828125
Epoch = 2, Loss = 383.375
Epoch = 3, Loss = 205.92941284179688
Epoch = 4, Loss = 27.954395294189453


In [ ]:
# Generate predictions/inference
preds = model(X[:10])
preds

In [84]:
# saving model

torch.save(model.state_dict(), 'pytorch_linear_regression_model.pkl')